import type { NextPage } from 'next';
import Head from 'next/head';

import { NewsCardList, Pagination, NewsCardItem } from 'components/shared';
import { newsAPI } from 'store/queries';
import { useAppDispatch, useAppSelector } from 'common/hooks';
import { toggleOne } from 'store/features/bookmark';
import { NewsItem } from 'common/types';

const News: NextPage = () => {
  const { data: news = [] } = newsAPI.useFetchCompanyNewsQuery({
    symbol: 'AAPL',
    from: '2022-04-01',
    to: '2022-06-01',
  });
  const bookmarkIds = useAppSelector((state) => state.bookmark.ids);
  const dispatch = useAppDispatch();

  const handleNewsItemSave = (newsItem: NewsItem) => {
    dispatch(toggleOne(newsItem));
  };

  return (
    <div>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex h-screen">
        {/* <div className="h-1/2 mr-6">
          <NewsCardItem itemData={latestNewsItem} isLatest />
        </div> */}
        <div>
          <NewsCardList
            data={news}
            bookmarkIds={bookmarkIds as number[]}
            onNewsItemSaveToggle={handleNewsItemSave}
          />
          <Pagination totalPages={24} perPageNumber={6} />
        </div>
      </div>
    </div>
  );
};

export default News;
