import type { NextPage } from 'next';
import Head from 'next/head';

import { NewsCardList, Pagination } from 'components/shared';
import { getCompanyNews } from 'api/company';

interface Props {
  news: any[];
}

const News: NextPage<Props> = ({ news }) => {
  return (
    <div>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NewsCardList data={news} />
      <Pagination totalPages={24} perPageNumber={6} />
    </div>
  );
};

export const getServerSideProps = async () => {
  const from = '2022-04-01';
  const to = '2022-06-01';
  const companyNews = await getCompanyNews({ symbol: 'AAPL', from, to });
  return {
    props: {
      news: companyNews.filter((_, index) => index < 6),
    },
  };
};

export default News;
